version: '3.8'

services:
  client:
    image: localhost/deep-presentation-client:latest
    # build:
    #   context: ./deep-presentation-client   # Path to your frontend Dockerfile
    ports:
      - "8501:8501"         # Exposing frontend on port 3000 (change if necessary)
    volumes:
      - ./shared:/app/shared:rw # Mounts shared directory to /app/shared in backend container
    environment:
      - API_URL=http://api:8082
      - VIDEO_STORAGE=/app/shared
  api:
    image: localhost/deep-presentation-api:latest
    # build:
    #   context: ./deep-presentation-api    # Path to your backend Dockerfile
    ports:
      - "8082:8082"
    volumes:
      - ./shared:/app/shared:rw # Mounts shared directory to /app/shared in backend container
    environment:
      - OPENAI_API_KEY=sk-...
      - WHISPERX_API=http://whisperx_api:8081
      - VIDEO_STORAGE=/app/shared
  whisperx_api:
    image: localhost/deep-presentation-whisperx:latest
    # build:
    #   context: ./whisperx-fin    # Path to your backend Dockerfile
    ports:
      - "8081:8081"
